# docker-compose.yml
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y" # Requerido
      MSSQL_SA_PASSWORD: "xY5bq1GpkauHvX56!" # Tómalo del .env
      MSSQL_PID: "Developer" # Developer para dev/pruebas
      MSSQL_AGENT_ENABLED: "true" # Habilita SQL Agent
      MSSQL_TCP_PORT: "1433"
      # MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"  # (opcional, solo tiene efecto en la 1ª init)
    volumes:
      - mssql-data:/var/opt/mssql # Persistencia de datos
    healthcheck:
      # Prueba SELECT 1 con sqlcmd (ruta tools18 o tools clásica)
      test:
        [
          "CMD-SHELL",
          '(/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1") >/dev/null 2>&1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9001"


volumes:
  mssql-data:
